install:
- bundle update --bundler
- bundle install
services:
- postgresql
script:
- bundle exec bin/rails db:create
- bundle exec bin/rails db:migrate
- bundle exec bin/rails db:environment:set RAILS_ENV=test
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: PcYjTy5T8Akr4ClituLC2kSvfRq1wEMvoGi9jHW7l1v+7cU+8kMgj5FaqSpXc1fFKtPnbfJhhdww03oVeWK2phDyMW4GHa85PVPllsStvueWVy/o7xFZcqDnkIqzgJ2iWRqxsvWW0cQrX7htRmop06g9t6zUgrcppSkxIX8ePn+BPeHuAH7ViiobYF5rN6z3mP+naZDrNQCUXiOniNCebuBKEp1/SMv6hB3S05n4rGvjpprWIfEAJFgjc6bM360PbQEjMsgLKQ+fG1js/J/uR48T1ZkvWbojor+rZHkzFEWOJoywf11+/Z8o87uK1eZAw7BX50GrL7uddUQSPp9Yd6T7dUL4A20omx2USyjXp/B6/fPb95dL0u8U/sUeasbJ9vNw7d5EjeNS9jGVN1suFzIKyp2DGvUvI2ofiwFVvrGzlP6qm854QHNpL+QEy1Gr9BSJgigKoNna0KfyVHumgA1qXLBhUWNLWGRCpA0bTQZ8zSRSSFyAnWqMCzusuxCEtgEQedLr+jnWZALPz9lmDK/MbFcOn9FkXDITr+j9vn2wIwRrzeGZ6BqtK225Fm7b1AG36TuGWaRrnZjImQKGK/238v3zr248JohMuj4fNUsjEX6TZF3/Enp8J6mDVxs/Y1T1ovJEItG8QxRFrWR/iL6/NJdjHxUJXHdeZriDG3k=
  app: limitless-fortress-82053
  edge: true
  run: rake db:migrate
